##
## EPITECH PROJECT, 2019
## makefile
## File description:
## makefile compiler
##

SRC	=	my_params_to_list.c	\

FLAGS	=	-L./lib/ -libmy.a

$(NAME):	$(NAME)
	@gcc -c $(FLAGS)
	@cp libmy.a ../
	@cp my.h ../../include/

clean:
	@rm -f 
